// terms page
// import tailwind global CSS
import '../styles/globals.css'

// use a container too
import { Container}  from '@mantine/core'

// here's the main dish
export default function Terms() {
    return <div className="min-h-[100vh] mt-10 mb-10">
        <Container size="xl">
        <h1 className="font-bold mb-1 text-lg">TERMS OF USE</h1>
        <p>In addition to the Terms of Use described below, please also review our “Disclaimers” page (accessible via the link in our website footer).</p>
        <p className="mb-1 mt-3">Please read these Terms and Conditions before using, or submitting content in any form or medium for publication on the ADVISER ELITE site. By continuing to use, or by submitting content for publication on ADVISERELITE.com, you agree to abide, and that you are bound, by these Terms and Conditions. We reserve the right to change these Terms and Conditions at any time, and you agree (including by virtue of your continued use of our site) to be bound by any such changes. Unless explicitly stated otherwise, any new features or functionality (including, without limitation, video and related projects) that augment or enhance our site shall be subject to these Terms and Conditions. The most current version of these Terms and Conditions can be viewed at any time at ADVISERELITE.com.</p>
        <p className="mb-1 mt-3">&mdash; We May Discontinue or Suspend Our Site or Terminate Your Use: We reserve the right at any time and from time to time to modify or discontinue, temporarily or permanently, our site (or any part thereof) with or without notice. You agree that ADVISER ELITE shall not be liable to you or any third party for any such modification, suspension or discontinuance of our site. In addition, we reserve the right to terminate your access to our site for any reason, and to take any other actions that ADVISER ELITE in its sole discretion, believes to be in the interest of our company and of our users as a whole.</p>
        <p className="mb-1 mt-3">&mdash; We Have All Rights In Our Site and Content; You Grant Us Certain Rights When You Submit Content to Us:</p>
        <ul className="list-disc ml-5">
            <li className="mb-1 mt-3">Our site and all content (including all text, photographs, graphics, video and audio content) posted by us is protected by copyright under the copyright laws of the United States and other countries, and we (subject to the rights of our licensors and licensees under applicable agreements, understandings and arrangements) have all rights therein. All individual articles, blogs, videos, content and other elements comprising our site posted by others are also copyrighted works, and the posters (subject to the rights of others) have all rights therein. You must abide by all additional copyright notices or restrictions contained on our site.</li>
            <li className="mb-1 mt-3">By posting or submitting content on or to our site (regardless of the form or medium with respect to such content, whether text, videos, photographs, audio or otherwise), you are giving us, and our affiliates, agents and third party contractors the right to display or publish such content on our site and its affiliated publications (either in the form submitted or in the form of a derivative or adapted work), to store such content, and to distribute such content and use such content for promotional and marketing purposes. Without limiting the generality of the foregoing, with respect to any video submissions to us made by you from time to time, you understand and agree that (unless you and we agree otherwise) we may, or may permit users to, based solely on functionality provided and enabled by our website, compile, re-edit, adapt or modify your video submission, or create derivative works therefrom, either on a stand-alone basis or in combination with other video submissions, and (unless you and we agree otherwise) you shall have no rights with respect thereto and we or our licensees shall be free to display and publish the same (as so compiled, re-edited, adapted, modified or derived) for any period.</li>
            <li className="mb-1 mt-3">You shall be solely responsible for your own submissions and the consequences of posting or publishing them. In connection with each of your submissions, you affirm, represent, and/or warrant that: (I) you own or have the necessary licenses, rights, consents, and permissions to use and authorize us to use all patent, trademark, trade secret, copyright or other proprietary rights in and to any and all such submissions to enable inclusion and use of such submissions in the manner contemplated by us and these Terms and Conditions; and (II) you have the written consent, release, and/or permission of each and every identifiable individual person in such submissions to use the name or likeness of each and every such identifiable individual person to enable inclusion and use of such submissions in the manner contemplated by us and these Terms and Conditions. In furtherance of the foregoing, you agree that you will not: (I) submit material that is copyrighted, protected by trade secret or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights or have permission from their rightful owner to post the material and to grant us all of the rights granted herein; (II) publish falsehoods or misrepresentations that could damage us or any third party; (III) submit material that is unlawful, obscene, defamatory, libelous, threatening, pornographic, harassing, hateful, racially or ethnically offensive, or encourages conduct that would be considered a criminal offense, give rise to civil liability, violate any law, or is otherwise inappropriate; or (IV) post advertisements or solicitations of business. We reserve the right to remove or not publish submissions without prior notice. You understand that when you submit content in any form to ADVISERELITE.com we may authorize such content to be distributed or syndicated to or published on other ADVISER ELITE-branded environments. Please be advised that our site uses services and products protected by one or more of U.S. Patent Nos. and patents pending.</li>
        </ul>
        <p className="mb-1 mt-3">&mdash; You Have Rights if You Believe Your Copyright is Being Infringed: If you are a copyright owner or agent thereof and believe that any of our content infringes upon your copyright, please click here (link to info@ADVISERELITE.com)</p>
        <p className="mb-1 mt-3">&mdash; Your Use of Our Content is Restricted:</p>
        <ul className="list-disc ml-5">
            <li className="mb-1 mt-3">Unless expressly permitted, you may not copy, reproduce, distribute, publish, enter into a database, display, perform, modify, create derivative works from, transmit or in any way exploit any part of our site or any content thereon, except as permitted under the last sentence of this Section 4(a) and except that you may make one print copy that is limited to occasional articles of personal interest only. Without limiting the generality of the foregoing (but subject to the last sentence of this Section 4(a)), you may not distribute any part of this site or any content thereon over any network, including, without limitation, a local area network, or sell or offer it for sale. In addition, these files may not be used to construct any kind of database. Just as we from time to time excerpt materials from other sources in order to support the various commentaries and writings contained herein, we respect the right of others to make “fair use” of the materials contained on our site; accordingly, you may from time to time excerpt and use materials set forth on this site consistent with the principles of “fair use”.</li>
            <li className="mb-1 mt-3">We are concerned about the integrity of our site when it is viewed in a setting created by a third party that includes advertising or other materials that we have not authorized to be displayed with the content of our site. Neither you nor any third party shall make use of the contents of our site in any manner that constitutes an infringement of our rights, including copyright or that has not been authorized by us.</li>
        </ul>
        <p className="mb-1 mt-3">&mdash; We are an Internet Service Provider, e.g., We are Not Responsible For and Do Not Necessarily Hold the Opinions Expressed by Our Content Contributors: Opinions and other statements expressed by users and third parties (e.g., bloggers) are theirs alone, not opinions of ADVISER ELITE. Content created by third parties is the sole responsibility of the third parties and its accuracy and completeness are not endorsed or guaranteed. You acknowledge that by providing you with the ability to view and distribute content through our site, ADVISER ELITE is not undertaking any obligation or liability relating to the content. ADVISER ELITE and its affiliates, successors, assigns, employees, agents, directors, officers and shareholders do not undertake or assume any duty to monitor our site for inappropriate or unlawful content. ADVISER ELITE  and its affiliates, successors, assigns, employees, agents, directors, officers and shareholders assume no responsibility or liability which may arise from the content thereof, including, but not limited to, claims for defamation, libel, slander, infringement, invasion of privacy and publicity rights, obscenity, pornography, profanity, fraud, or misrepresentation. Notwithstanding the foregoing, ADVISER ELITE reserves the right to block or remove communications, postings or materials at any time in our sole discretion.</p>
        <p className="mb-1 mt-3">&mdash; You Will Be Responsible for Any Harm We Suffer as a Result of Your Violation of These Terms and Conditions or Any Breach by You of Your Representations and Warranties: You agree to indemnify and hold harmless ADVISER ELITE and its affiliates, and their respective members, directors, officers, managers, employees, shareholders, agents, and licensors, from and against all losses, expenses, damages and costs, including reasonable attorneys’ fees, resulting from any violation by you of these Terms and Conditions or any breach by you of your representations and warranties hereunder. We reserve the right to take over the exclusive defense of any claim for which we are entitled to indemnification under this Section 6. In such event, you shall provide us with such cooperation as is reasonably requested by us.</p>
        <p className="mb-1 mt-3">&mdash; Your Use of Our Site is Subject to Certain Disclaimers: OUR SITE IS AVAILABLE “AS IS.” WE DO NOT WARRANT THAT OUR SITE WILL BE UNINTERRUPTED OR ERROR-FREE. THERE MAY BE DELAYS, OMISSIONS, INTERRUPTIONS AND INACCURACIES IN THE NEWS, INFORMATION OR OTHER MATERIALS AVAILABLE THROUGH OUR SITE. WE DO NOT MAKE ANY WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, THOSE OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, WITH RESPECT TO OUR SITE OR ANY INFORMATION OR GOODS THAT ARE AVAILABLE OR ADVERTISED OR SOLD THROUGH OUR SITE. WE DO NOT MAKE ANY REPRESENTATIONS, NOR DO WE ENDORSE THE ACCURACY, COMPLETENESS, TIMELINESS OR RELIABILITY OF ANY ADVICE, OPINION, STATEMENT OR OTHER MATERIAL OR DATABASE DISPLAYED, UPLOADED OR DISTRIBUTED ON THIS SITE OR AVAILABLE THROUGH LINKS ON OUR SITE. WE RESERVE THE RIGHT TO CORRECT ANY ERRORS OR OMISSIONS ON OUR SITE. ALTHOUGH WE INTEND TO TAKE REASONABLE STEPS TO PREVENT THE INTRODUCTION OF VIRUSES, WORMS, “TROJAN HORSES” OR OTHER DESTRUCTIVE MATERIALS TO OUR SITE, WE DO NOT GUARANTEE OR WARRANT THAT OUR SITE OR MATERIALS THAT MAY BE DOWNLOADED FROM OUR SITE DO NOT CONTAIN SUCH DESTRUCTIVE FEATURES. WE ARE NOT LIABLE FOR ANY DAMAGES OR HARM ATTRIBUTABLE TO SUCH FEATURES. IF YOU RELY ON OUR SITE AND ANY MATERIALS AVAILABLE THROUGH OUR SITE, YOU DO SO SOLELY AT YOUR OWN RISK. OUR SITE MAY CONTAIN VARIOUS COMBINATIONS OF TEXT, IMAGES, AUDIOVISUAL PRODUCTIONS, OPINIONS, STATEMENTS, FACTS, ARTICLES, MARKET DATA, STOCK QUOTES OR OTHER INFORMATION CREATED BY US OR BY THIRD-PARTIES. DUE TO THE NUMBER OF SOURCES FROM WHICH CONTENT ON OUR SITE IS OBTAINED, AND THE INHERENT HAZARDS OF ELECTRONIC DISTRIBUTION, THERE MAY BE DELAYS, OMISSIONS OR INACCURACIES IN SUCH CONTENT. ACCORDINGLY, SUCH CONTENT, INCLUDING MARKET DATA, IS FOR YOUR REFERENCE ONLY AND SHOULD NOT BE RELIED UPON BY YOU FOR ANY PURPOSE. SUCH CONTENT IS NOT INTENDED FOR THE PURPOSE OF TAX OR INVESTMENT ADVICE AND IT DOES NOT ADVOCATE THE PURCHASE OR SALE OF ANY SECURITY OR INVESTMENT. INFORMATION CREATED BY THIRD PARTIES THAT YOU MAY ACCESS ON OUR SITE OR THROUGH LINKS IS NOT ADOPTED OR ENDORSED BY US AND REMAINS THE RESPONSIBILITY OF SUCH THIRD PARTIES</p>
        <p className="mb-1 mt-3">&mdash; We are Not Responsible for Linked Sites: We are not responsible for the availability or content of other services that may be linked to our site. Because we have no control over such services, you acknowledge and agree that we are not responsible for the availability of such external services, and that we do not endorse and are not responsible or liable for any content, accuracy, quality, advertising, products or other materials on or available from such services. You further acknowledge and agree that we shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any content, goods or services available on or through such services.</p>
        <p className="mb-1 mt-3">&mdash; We May be Legally Compelled to Disclose Certain Information: You agree that in the event we receive a subpoena issued by a court or from a law enforcement or government agency, we shall comply with such subpoenas without your consent or prior notice to you and may disclose your IP address, username, name, IP location or other information in response thereto</p>
        <p className="mb-1 mt-3">&mdash; Our Liability to You is Limited: ADVISER ELITE and its affiliates, and their respective members, directors, officers, managers, employees, shareholders, agents and licensors are not liable for incidental, indirect, consequential, special, punitive, or exemplary damages of any kind, including, without limitation, lost revenues or profits, loss of business or loss of data, in any way related to this site or for any claim, loss or injury based on errors, omissions, interruptions or other inaccuracies in our site (including, without limitation, as a result of breach of any warranty or other term of these Terms and Conditions). Any claim against us shall be limited to the amount you paid, if any, for use of our site.</p>
        <p className="mb-1 mt-3">&mdash; Any Dispute Between Us Will be Governed by California Law: These Terms and Conditions shall be governed by the laws of the United States and the State of California, applicable to agreements made and to be performed therein without regard to conflict of laws principles. BY CONTINUING TO USE OUR SITE, YOU AGREE TO ABIDE BY THESE TERMS AND CONDITIONS. The caption to each Section of these Terms and Conditions are for convenience of reference only and shall be ignored in the construction or interpretation hereof.</p>
        </Container>
    </div>
}